// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Blob Creatures",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "Blob Creatures",
            targets: ["AppModule"],
            bundleIdentifier: "blobCreatures",
            teamIdentifier: "J75UGCLYPW",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .lightningBolt),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/gadirom/TransformGesture", "0.0.1"..<"1.0.0"),
        .package(url: "https://github.com/MetalBuilder/MetalBuilder", "0.3.0"..<"0.4.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "TransformGesture", package: "transformgesture"),
                .product(name: "MetalBuilder", package: "metalbuilder")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)